# Generated by Django 5.0.4 on 2024-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
